### ISSUE TITLE
Band mit mehreren "Book manuscripts"-PDFs

### ISSUE THREAD

**Issue by kadowa** [UB-Heidelberg/UBHD-OMPHeibooks#1]
Bei http://books.ub.uni-heidelberg.de/index.php/heibooks/catalog/book/69 sind drei Dateien als "Book Manuscript" gekennzeichnet, dadurch werden wieder mehrere Download-Buttons erzeugt.

![heibooks_69](https://cloud.githubusercontent.com/assets/8066366/13431999/1622cadc-dfcc-11e5-8163-09ee4572abdf.png)

Hier die entsprechenden Dateien in der DB (`genre_id` 3 bedeutet "Book manuscript"):

![db_69](https://cloud.githubusercontent.com/assets/8066366/13432014/1e8f49d4-dfcc-11e5-9c89-6a10855d69dc.png)

@AnjaKonopka, könntest du die Einreichung bei Gelegenheit mal überprüfen? Nur eine Datei sollte "Book manuscript" sein.

**Comment by ankosi** [comment]
@kadowa , @UB-Heidelberg/omp_users Ich habe die Book-Manuscript-Dateien durch "Chapter manuscript"-Dateien ersetzt.

Übrigens kann man doch Dateien mit einer falschen Genre-Bezeichnung so ersetzen, dass die Reihenfolge erhalten bleibt und das Genre neu zugeordnet wird: Dazu muss man die falsche Datei zunächst noch im OMP behalten, lädt dann eine neue hoch und gibt aber nicht an, welches Kapitel ersetzt werden soll. Auszuwählen im Drop-down-Menü ist also "Select file (to preserve history)". Wenn man dann auf "Continue" geht, fragt das System selbst noch einmal nach, ob man nicht eine bestehende Datei austauschen möchte, weil die Dateinamen so ähnlich sind. An dieser Stelle kann man dann auch ein neues Genre vergeben.
![2016-03-02 13_48_13-file_upload](https://cloud.githubusercontent.com/assets/11088169/13460818/c36daeda-e07d-11e5-9ba5-580db6ca06ff.png)

**Comment by kadowa** [comment]
This issue was moved to UB-Heidelberg/UBHD-OMPPortal#2
