### ISSUE TITLE
Seriencover wird nicht angezeigt

### ISSUE THREAD

**Issue by dastewo** [UB-Heidelberg/UBHD-OMPHeibooks#2]
@kadowa wie besprochen hier der Screenshot:
![bildschirmfoto vom 2016-03-02 11 06 43](https://cloud.githubusercontent.com/assets/15866252/13457129/c4f87648-e066-11e5-8549-f3db4ebb6ace.png)

**Comment by kadowa** [comment]
Das ist aber UBHD_OMPHeibooks, oder? Mit heibooks hast du das Problem nicht?

**Comment by dastewo** [comment]
Nein, die Sache sieht anders aus:
Bisher war an dieser Stelle ein Cover, das wir einmal manuell eingepflegt haben, quasi als Dummy. Nun aber soll das Cover aus OMP kommen, wie es bei Propylaeum schon der Fall ist. Ich habe daher den Code, den wir bei Propylaeum verwendet haben, in UBHDHeibooks hinein kopiert.
Ich habe noch keinen Commit gemacht, daher sieht man das in heibooks auch noch nicht.

**Comment by kadowa** [comment]
Ah, ok, jetzt wird die Sache klarer. Ich gucke gleich mal ...

**Comment by kadowa** [comment]
So, das Cover sollte jetzt da sein: http://heiup.uni-heidelberg.de/UBHD_OMPHeibooks/series

Für heibooks hab ich auch entsprechend verlinkt, d.h. nach Commit deiner Änderungen müsste es dort auch erscheinen.

**Comment by dastewo** [comment]
Ja, danke :-)
