### ISSUE TITLE
Neues Publikationsformat anlegen

### ISSUE THREAD

**Issue by ankosi** [UB-Heidelberg/UBHD-OMPHeibooks#3]
@kadowa, @withanage, Bei dem Band "Religion in Ex-Position" habe ich mal den Versuch gestartet, auf einer eigenen Registerkarte das Format "Softcover" anzulegen. Dort habe ich alle relevanten Informationen eingetragen (ISBN, Imprint, Erscheinungsdatum etc.). Als Datei habe ich die Titelei hinterlegt, und zwar als "Chapter manuscript" (als "Book Manuscript" bekam ich gleich wieder den zweiten Downloadbutton im Frontend angezeigt.). 

Im Submission -> Production habe ich bei ""Proof", "Catalog" und "Available" habe ich den Haken gesetzt:

![2016-03-02_neue_registerkarte_softcover](https://cloud.githubusercontent.com/assets/11088169/13462157/2f401e24-e086-11e5-8fb4-bbefd787a9c9.png)

Im Catalog aber die Datei nicht auf "available" gesetzt, damit sie nicht nochmals auf der Website zum Download angeboten wird.

![2016-03-02_softcover_catalog-angaben](https://cloud.githubusercontent.com/assets/11088169/13462206/868ae75e-e086-11e5-9720-d15c680da483.png)

Auf der Website werden nun immerhin schon mal die Print- und die PDF-ISBN sauber getrennt ausgegeben. Es scheint also, als wäre alles gut gegangen. Könnten wir dieses Modell dann auch für die anderen Verlage nehmen?

http://heiup.uni-heidelberg.de/UBHD_OMPHeibooks/catalog/book/69

**Comment by kadowa** [comment]
This issue was moved to UB-Heidelberg/UBHD-OMPPortal#3
