### ISSUE TITLE
Zitierweise ISBN und Erscheinungsjahr bei unterschiedlichen Publikationsformaten

### ISSUE THREAD

**Issue by ankosi** [UB-Heidelberg/UBHD-OMPHeibooks#4]
@kadowa, @withanage 

Darstellung von Erscheinungsdatum und ISBN, wenn wir
1. Print  und PDF
2. Print (nicht mehr lieferbar) und PDF
3. Print (nicht mehr lieferbar), Print (lieferbar durch uns) und PDF haben.

Das Ergebnis ist:

Wenn Buch und Online-PDF beim gleichen Verlag (also bei uns) erscheinen und das Erscheinungsjahr das gleiche ist, nennen wir das Erscheinungsjahr in der empfohlenen Zitierung hinter dem Verlag, angeschlossen mit einem Komma : 

> Empfohlene  Zitierweise 
>    Autorname Vorname:
>  Titel. Ort, Verlag, Jahr. doi ....

Bei den ISBNs nennen wir hingegen beide, PDF und Print, an der Stelle, an der bisher schon die PDF-ISBN steht, in der Form:

> ISBN:  1234568909384 (PDF) [vom Reiter PDF]
> ISBN: xxxx (Buch ) [-> vom Reiter Softcover/Hardcover]

   Wenn Buch Online-PDF ursprünglich in einem anderen Verlag erschienen ist, beziehen wir uns bei der empfohlenen Zitierweise auf das PDF. Bsp.:

> Nachname, Vorname:
> Titel. Ort: Verlag Jahr

Unterhalb von "Veröffentlicht am 23.07.2015" schreiben wir dann:

> Originalveröffentlichung  bei ... [= Verlagsname] im Jahr ... [Erscheinungsjahr].

Bei den ISBNs nennen wir ebenfalls beide, und zwar so:

>  ISBN: 12234343434323 (PDF)
>     ISBN: xxxx (Orig.-Ausg.)

 Wenn das Buch als Originalveröffentlichung vergriffen ist, Print on Demand (über uns) möglich ist und das PDF auf unserer Website herunterladbar ist, und sich zu allem Überfluss Print-on-Demand und PDF-Erscheinungsjahr unterscheiden, wird es natürlich schwierig. Ich würde dann ebenfalls unter "Veröffentlicht am ..." schreiben:

> Orig.-Ausg.  bei ... [= Verlagsname] ... [Erscheinungsjahr]
>     Buchausg. bei ... [z. B. Verlag] ... [Erscheinungsjahr]

Bei den ISBNs nennen wir alle drei:

>  ISBN: xxxxx (PDF)
>     ISBN: xxxx (Orig.-Ausg.)
>     ISBN: xxxx (Buchausg. Verlag)

 Das Erscheinungsjahr des PDF ziehen wir vom Reiter PDF, dort ist es "Publication date".
Das Erscheinungsjahr der Originalveröffentlichung am besten von einem eigenen Reiter "Originalveröffentlichung", damit wir auch dort die ISBN und den Verlag eingeben können, als Bezug für das Datum wählen wir "Publication date of print counter part"
    Das Erscheinungsjahr der PoD-Veröffentlichung von einem Reiter "Softcover" oder "Hardcover" (je nachdem, was es ist), dort kann die Bezeichnung für das Datum schwanken, da es sich ja auch um eine Neuauflage handeln kann. Auf diesem Reiter sollten wir ebenfalls ISBN und Verlag eingeben.

**Comment by ankosi** [comment]
@kadowa, Ich hoffe, ich treibe Dich nicht in den Wahnsinn, aber: Jetzt erscheint auf der deutschen Seite als Anzeigensprache Englisch.

**Comment by kadowa** [comment]
Damit kämpfe ich gerade. /o\

Am 11.03.2016 um 13:07 schrieb ankosi:

**Comment by kadowa** [comment]
Das Problem betrifft übrigens gerade alle Übersetzungen, nicht wundern.

Am 11.03.2016 um 13:07 schrieb ankosi:
