### ISSUE TITLE
Kurzbiografien- Ausgabe mehrerer Kurzbiografien als nur einer

### ISSUE THREAD

**Issue by ankosi** [UB-Heidelberg/UBHD-OMPHeibooks#5]
Zur Zeit wird nur eine (vermutlich die erste) Kurzbiografie auf dem Frontend ausgegeben. Wir haben - vor allem bei Sammelbänden - aber meist mehrere Autoren oder Herausgeber. Bitte möglichst die Ausgabe von drei Kurzbiografien ermöglichen.

**Comment by kadowa** [comment]
This issue was moved to UB-Heidelberg/UBHD-OMPPortal#4
