### ISSUE TITLE
Kurzbiografien - Anmoderation

### ISSUE THREAD

**Issue by ankosi** [UB-Heidelberg/UBHD-OMPHeibooks#6]
Solange es keine Möglichkeit gibt, automatisch zu erkennen, ob der Autor/Herausgeber männlich oder weiblich ist, sollte die Anmoderation lauten:

Über den Autor/die Autorin
Über den Herausgeber/die Herausgeberin

**Comment by ankosi** [comment]
@kadowa, ich habe Anmoderation wie von dir vorgeschlagen in die Kurzbiographie gesetzt und - wenn es mehrere Autoren bzw. Hrsg. gibt, alle in einer Kurzbiographie eingetragen. Kannst du die Anzeige der Kurzbiographien wieder aktivieren (ist ja zurzeit deaktiviert) damit wir das Ergebnis sehen?

**Comment by kadowa** [comment]
This issue was moved to UB-Heidelberg/UBHD-OMPPortal#5
