### ISSUE TITLE
Reiheninformationen

### ISSUE THREAD

**Issue by ankosi** [UB-Heidelberg/UBHD-OMPHeibooks#7]
@kadowa,  @UB-Heidelberg/omp 
Die Information Reihe + Band, also z. B. Universitätsmuseum Heidelberg – Kataloge, Band 11
soll auch bei der Einstiegsseite in den Katalog

http://books.ub.uni-heidelberg.de/heibooks/catalog

beim jeweiligen Band angezeigt werden.

**Comment by kadowa** [comment]
Ergänzung von ef: Anzeige auch auf der Buchseite (http://books.ub.uni-heidelberg.de/heibooks/catalog/book/73), idealerweise mit Link zur Reihe.

**Comment by kadowa** [comment]
This issue was moved to UB-Heidelberg/UBHD-OMPPortal#6
