### ISSUE TITLE
Doppelter Downloadbutton nach ausgetauschtem PDF

### ISSUE THREAD

**Issue by ghost** [UB-Heidelberg/UBHD-OMPHeibooks#8]
Nach dem Austausch eines PDFs vom Typ "Book Manuscript" erscheinen zwei Download-Buttons für das gleiche PDF:

http://books.ub.uni-heidelberg.de/heibooks/catalog/book/69

**Comment by kadowa** [comment]
This issue was moved to UB-Heidelberg/UBHD-OMPPortal#24
